"""Windows autostart — HKCU Run → VBS in ~/.bonjur-epta (retries, fixed cwd, always refresh).

Why this design:
- Old sync() skipped rewrite when the Run value already existed (want==have), so a
  moved install / another Python left a stale command → boots on login every
  other time.
- Writing a .vbs next to main.py fails under real Program Files (no write ACL).
  Script lives in the user config dir; it always points at the current app root.
- At login, cwd is often System32 and disks can lag; VBS sets CurrentDirectory,
  retries, and logs failures to ~/.bonjur-epta/autostart.log.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REG_PATH = r"Software\Microsoft\Windows\CurrentVersion\Run"
REG_NAME = "BonjurEpta"
STARTUP_FLAG = "--startup"
VBS_NAME = "bonjur-autostart.vbs"
CONFIG_DIR = Path.home() / ".bonjur-epta"


def supported() -> bool:
    return sys.platform == "win32"


def app_root() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parents[1]


def pythonw_path() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve()
    exe = Path(sys.executable).resolve()
    if exe.name.lower() == "python.exe":
        pyw = exe.with_name("pythonw.exe")
        if pyw.is_file():
            return pyw
    return exe


def _vbs_path() -> Path:
    return CONFIG_DIR / VBS_NAME


def _wscript() -> Path:
    root = Path(os.environ.get("SystemRoot", r"C:\Windows"))
    return root / "System32" / "wscript.exe"


def _vbs_quote(s: str) -> str:
    return s.replace('"', '""')


def write_launcher_script() -> Path:
    """Regenerate ~/.bonjur-epta/bonjur-autostart.vbs for this install."""
    root = app_root()
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    vbs = _vbs_path()
    main_py = root / "main.py"
    pyw = pythonw_path()
    root_s = _vbs_quote(str(root.resolve()))
    exe_s = _vbs_quote(str(pyw.resolve()))
    main_s = _vbs_quote(str(main_py.resolve()))
    # VBS quote hell: build Run lines without nested Python f-string quotes.
    run_pyw = (
        'sh.Run """" & exe & """ """ & main & """ '
        + STARTUP_FLAG
        + '", 0, False'
    )
    run_launcher = (
        'sh.Run "pyw -3 """ & main & """ '
        + STARTUP_FLAG
        + '", 0, False'
    )
    run_py = (
        'sh.Run "py -3 """ & main & """ '
        + STARTUP_FLAG
        + '", 0, False'
    )
    body = "\r\n".join(
        [
            "Option Explicit",
            "' Auto-generated by Bonjur-epta - rewritten on every autostart sync.",
            "Dim sh, fso, logPath, exe, main, i, parent, ts, line, stream",
            'Set sh = CreateObject("WScript.Shell")',
            'Set fso = CreateObject("Scripting.FileSystemObject")',
            f'sh.CurrentDirectory = "{root_s}"',
            f'exe = "{exe_s}"',
            f'main = "{main_s}"',
            (
                'logPath = sh.ExpandEnvironmentStrings("%USERPROFILE%")'
                ' & "\\.bonjur-epta\\autostart.log"'
            ),
            "On Error Resume Next",
            "parent = fso.GetParentFolderName(logPath)",
            "If Not fso.FolderExists(parent) Then fso.CreateFolder parent",
            "Err.Clear",
            "For i = 1 To 8",
            "  If fso.FileExists(main) Then",
            "    If fso.FileExists(exe) Then",
            "      Err.Clear",
            f"      {run_pyw}",
            "      If Err.Number = 0 Then WScript.Quit 0",
            "    End If",
            "    Err.Clear",
            f"    {run_launcher}",
            "    If Err.Number = 0 Then WScript.Quit 0",
            "    Err.Clear",
            f"    {run_py}",
            "    If Err.Number = 0 Then WScript.Quit 0",
            "  End If",
            "  WScript.Sleep 1500",
            "Next",
            "ts = Now",
            (
                'line = ts & " FAIL main=" & main & " exe=" & exe'
                ' & " err=" & Err.Description'
            ),
            "Set stream = fso.OpenTextFile(logPath, 8, True)",
            "stream.WriteLine line",
            "stream.Close",
            "WScript.Quit 1",
            "",
        ]
    )
    vbs.write_text(body, encoding="utf-8", newline="\r\n")
    return vbs


def launch_command() -> str:
    """Command written to the Run key."""
    if getattr(sys, "frozen", False):
        exe = Path(sys.executable).resolve()
        return f'"{exe}" {STARTUP_FLAG}'

    vbs = write_launcher_script()
    ws = _wscript()
    return f'"{ws}" //B //Nologo "{vbs.resolve()}"'


def registered_command() -> str | None:
    if not supported():
        return None
    import winreg

    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REG_PATH) as key:
            val, _ = winreg.QueryValueEx(key, REG_NAME)
            return str(val) if val else None
    except OSError:
        return None


def is_enabled() -> bool:
    return registered_command() is not None


def set_enabled(on: bool) -> tuple[bool, str | None]:
    """Apply or remove Run entry. When on=True, always rewrite VBS + registry value."""
    if not supported():
        return False, "только Windows"
    import winreg

    try:
        if on:
            if not (app_root() / "main.py").is_file() and not getattr(sys, "frozen", False):
                return False, "main.py не найден"
            cmd = launch_command()
            with winreg.CreateKeyEx(
                winreg.HKEY_CURRENT_USER, REG_PATH, 0, winreg.KEY_SET_VALUE
            ) as key:
                winreg.SetValueEx(key, REG_NAME, 0, winreg.REG_SZ, cmd)
        else:
            try:
                with winreg.OpenKey(
                    winreg.HKEY_CURRENT_USER, REG_PATH, 0, winreg.KEY_SET_VALUE
                ) as key:
                    winreg.DeleteValue(key, REG_NAME)
            except FileNotFoundError:
                pass
            try:
                vp = _vbs_path()
                if vp.is_file():
                    vp.unlink()
            except OSError:
                pass
        return True, None
    except OSError as exc:
        return False, str(exc)


def sync(want: bool) -> tuple[bool, str | None]:
    """Ensure registry matches the settings flag.

    When want=True, always refresh VBS + Run command (never skip on 'already on').
    That keeps the login path correct after moves / Python reinstalls.
    """
    if not want:
        if is_enabled():
            return set_enabled(False)
        return True, None
    return set_enabled(True)
